"""Shared enums and evidence states — scientific integrity contracts."""

from enum import StrEnum


class ProcessingState(StrEnum):
    RAW = "RAW"
    PREPROCESSED = "PREPROCESSED"
    SEGMENTED = "SEGMENTED"
    AGGLOMERATED = "AGGLOMERATED"
    SYNAPSE_PREDICTED = "SYNAPSE_PREDICTED"
    AUTO_RECONSTRUCTED = "AUTO_RECONSTRUCTED"
    PARTIALLY_PROOFREAD = "PARTIALLY_PROOFREAD"
    PROOFREAD = "PROOFREAD"
    ANNOTATED = "ANNOTATED"
    RELEASED = "RELEASED"


class EvidenceState(StrEnum):
    OBSERVED = "OBSERVED"
    MODEL_PREDICTED = "MODEL_PREDICTED"
    INFERRED = "INFERRED"
    MANUALLY_VERIFIED = "MANUALLY_VERIFIED"
    SOURCE_DOCUMENTED = "SOURCE_DOCUMENTED"
    UNKNOWN = "UNKNOWN"


class Suitability(StrEnum):
    CONNECTOME_READY = "CONNECTOME_READY"
    SEGMENTATION_READY = "SEGMENTATION_READY"
    SYNAPSE_RESOLUTION_PARTIAL = "SYNAPSE_RESOLUTION_PARTIAL"
    MORPHOLOGY_ONLY = "MORPHOLOGY_ONLY"
    TRAINING_DATA_ONLY = "TRAINING_DATA_ONLY"
    INSUFFICIENT_RESOLUTION = "INSUFFICIENT_RESOLUTION"
    INACCESSIBLE = "INACCESSIBLE"
    UNKNOWN = "UNKNOWN"


class CoverageClaim(StrEnum):
    WHOLE_CNS = "WHOLE_CNS"
    WHOLE_BRAIN = "WHOLE_BRAIN"
    BRAIN_REGION = "BRAIN_REGION"
    PARTIAL_VOLUME = "PARTIAL_VOLUME"
    ROI = "ROI"
    EXPERIMENTAL_AUTOMATED_RECONSTRUCTION = "EXPERIMENTAL_AUTOMATED_RECONSTRUCTION"
